name: Bug Report
description: Report a bug in the project
title: "[BUG]"
labels: bug
assignees: TheNoeTrevino
projects: "Tremolonotes"
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug
      placeholder: "1. Go to...\n2. Click on this..."
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expected to happen?
