name: Ticket Template
description: Default template for new issues
title: "[ISSUE]"
labels: [general]
assignees:
  - TheNoeTrevino
body:
  - type: markdown
    attributes:
      value: |
        **Description**
        Describe goal here

