name: Move issue to "Dev Done" when merged to main

# This workflow requires a Personal Access Token (PAT) with project permissions
# because the default GITHUB_TOKEN does not have access to GitHub Projects V2.
#
# Setup:
# 1. Create a PAT at https://github.com/settings/tokens with scopes: repo, project, read:project
# 2. Add it as a repository secret named PROJECT_TOKEN:
#    gh secret set PROJECT_TOKEN --body "<your-token>"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  move_to_dev_done:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issues to Dev Done
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const textToSearch = `${pr.title || ''} ${pr.body || ''}`;
            const issueRefs = textToSearch.match(/#(\d+)/g) || [];

            const PROJECT_ID = "PVT_kwHOCJZzqc4AoJ-p";
            const STATUS_FIELD_ID = "PVTSSF_lAHOCJZzqc4AoJ-pzgfxfns";
            const DEV_DONE_OPTION_ID = "1f78e38d";

            console.log(`Found ${issueRefs.length} issue references in PR title and body`);

            for (const ref of issueRefs) {
              const issueNumber = parseInt(ref.replace("#", ""));
              console.log(`Processing issue #${issueNumber}`);
              
              try {
                // Get the issue node ID
                const issue = await github.rest.issues.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber
                });
                
                console.log(`Issue #${issueNumber} node_id: ${issue.data.node_id}`);
                
                // Find the project item ID for this issue
                const projectItemQuery = `
                  query($issueId: ID!) {
                    node(id: $issueId) {
                      ... on Issue {
                        projectItems(first: 10) {
                          nodes {
                            id
                            project {
                              id
                            }
                          }
                        }
                      }
                    }
                  }
                `;
                
                const projectItemResult = await github.graphql(projectItemQuery, {
                  issueId: issue.data.node_id
                });
                
                const projectItem = projectItemResult.node.projectItems.nodes.find(
                  item => item.project.id === PROJECT_ID
                );
                
                if (!projectItem) {
                  console.log(`Issue #${issueNumber} is not in the Tremolonotes project, skipping`);
                  continue;
                }
                
                const updateMutation = `
                  mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                    updateProjectV2ItemFieldValue(
                      input: {
                        projectId: $projectId
                        itemId: $itemId
                        fieldId: $fieldId
                        value: { singleSelectOptionId: $optionId }
                      }
                    ) {
                      projectV2Item {
                        id
                      }
                    }
                  }
                `;
                
                await github.graphql(updateMutation, {
                  projectId: PROJECT_ID,
                  itemId: projectItem.id,
                  fieldId: STATUS_FIELD_ID,
                  optionId: DEV_DONE_OPTION_ID
                });
                
                console.log(`✅ Successfully moved issue #${issueNumber} to Dev Done`);
                
              } catch (error) {
                console.error(`Error processing issue #${issueNumber}:`, error.message);
              }
            }
