name: Require at least one label

on:
  issues:
    types: [opened, edited]

jobs:
  check_label:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure issue has a label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            if (!issue.labels || issue.labels.length === 0) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: '⚠️ Please add at least one label to this issue. No labels were found. ⚠️'
              });
            }
