name: Require PR Label

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check_label:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR has at least one label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;

            if (!pr.labels || pr.labels.length === 0) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: '⚠️ Please add at least one label to this PR. No labels were found. ⚠️'
              });
              core.setFailed('PR requires at least one label.');
            }
