name: Require Project Association

on:
  issues:
    types: [opened, edited]

jobs:
  check_project:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure issue is in a project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;

            const { data: items } = await github.graphql(`
              query ($issueId: ID!) {
                node(id: $issueId) {
                  ... on Issue {
                    projectItems(first: 1) {
                      nodes {
                        id
                      }
                    }
                  }
                }
              }
            `, { issueId: context.payload.issue.node_id });

            const projectItems = items.node.projectItems.nodes;

            if (!projectItems || projectItems.length === 0) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: '⚠️ Please add this issue to a project. No project association was found. ⚠️'
              });
            }
